yaml:
  integer: 1
  aDouble: 2.2
  aBoolean: false
  string: "\t233"
  string2: '\t233'
  localDateTime: 2022-08-18 12:03:21
  date: 2022-08-18 12:03:21
#  strings: [str1, str2]
  strings:
    - str1
    - str2
#  map: {k1:v1, k2:v2}
  map:
    k1: 1
    k2: 2
  set:
    - 555
    - 666
    - 777
  listMap:
    k3: [1, 2, 3]
    k4: [4, 5, 6]
  user:
    id: 1
    name: '\tzhangsan'